#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

m4 constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite

cp 0.org/* 0/
runApplication setFields
